interface OpenApiOperation {
  readonly operationId?: string;
  readonly summary?: string;
  readonly tags?: ReadonlyArray<string>;
}

interface OpenApiDocument {
  readonly paths?: Readonly<Record<string, Readonly<Record<string, OpenApiOperation>>>>;
}

const document = (await Bun.file(
  `${import.meta.dir}/../spec/affinity.openapi.json`,
).json()) as OpenApiDocument;

const clinicalOperations = new Set(["cancelOrder", "createOrderSigningSession", "createOrders"]);

const operations = Object.entries(document.paths ?? {}).flatMap(([path, pathItem]) =>
  Object.entries(pathItem).flatMap(([method, operation]) => {
    if (!operation.operationId) return [];
    const upperMethod = method.toUpperCase();
    return [
      {
        name: operation.operationId,
        method: upperMethod,
        path,
        summary: operation.summary ?? operation.operationId,
        tag: operation.tags?.[0] ?? "Other",
        kind:
          upperMethod === "GET" || upperMethod === "HEAD"
            ? "read"
            : clinicalOperations.has(operation.operationId)
              ? "clinical"
              : "write",
      },
    ];
  }),
);

operations.sort((left, right) => left.name.localeCompare(right.name));

const quoted = (value: string) => JSON.stringify(value);
const entries = operations
  .map(
    (operation) => `  ${operation.name}: {
    effect: Operations.${operation.name},
    method: ${quoted(operation.method)},
    path: ${quoted(operation.path)},
    summary: ${quoted(operation.summary)},
    tag: ${quoted(operation.tag)},
    kind: ${quoted(operation.kind)},
  },`,
  )
  .join("\n");

const source = `// AUTO-GENERATED by scripts/generate-code.ts. Do not edit.
import * as Operations from "../services/affinity.ts";

export const operationRegistry = {
${entries}
} as const;

export type OperationName = keyof typeof operationRegistry;
export type OperationKind = (typeof operationRegistry)[OperationName]["kind"];
`;

await Bun.write(`${import.meta.dir}/../src/code/registry.ts`, source);
