import { loadOpenApi } from "./openapi.ts";

interface OpenApiOperation {
  readonly operationId?: string;
  readonly parameters?: ReadonlyArray<{
    readonly in?: string;
    readonly name?: string;
    readonly required?: boolean;
  }>;
  readonly summary?: string;
  readonly tags?: ReadonlyArray<string>;
}

interface OpenApiDocument {
  readonly paths?: Readonly<Record<string, Readonly<Record<string, OpenApiOperation>>>>;
}

const document = (await loadOpenApi()) as OpenApiDocument;

const clinicalOperations = new Set([
  "cancelOrder",
  "actOnOrderException",
  "createOrder",
  "createOrderBatch",
  "addOrderPrescription",
  "updateOrderPrescription",
  "createHostedSession",
  "signOrder",
  "signAndSubmitOrder",
  "submitOrder",
  "rejectOrder",
  "updateOrderTestSimulation",
]);

const operations = Object.entries(document.paths ?? {}).flatMap(([path, pathItem]) =>
  Object.entries(pathItem).flatMap(([method, operation]) => {
    if (!operation.operationId) return [];
    const upperMethod = method.toUpperCase();
    return [
      {
        name: operation.operationId.replace(
          /[^a-zA-Z0-9]+([a-zA-Z0-9])/gu,
          (_match, letter: string) => letter.toUpperCase(),
        ),
        method: upperMethod,
        idempotencyRequired:
          operation.parameters?.some(
            (parameter) =>
              parameter.in === "header" &&
              parameter.name?.toLowerCase() === "idempotency-key" &&
              parameter.required,
          ) ?? false,
        path,
        summary: operation.summary ?? operation.operationId,
        tag: operation.tags?.[0] ?? "Other",
        kind:
          upperMethod === "GET" || upperMethod === "HEAD"
            ? "read"
            : clinicalOperations.has(operation.operationId)
              ? "clinical"
              : "write",
      },
    ];
  }),
);

operations.sort((left, right) => left.name.localeCompare(right.name));

const quoted = (value: string) => JSON.stringify(value);
const entries = operations
  .map(
    (operation) => `  ${operation.name}: {
    effect: Operations.${operation.name},
    method: ${quoted(operation.method)},
    idempotencyRequired: ${operation.idempotencyRequired},
    path: ${quoted(operation.path)},
    summary: ${quoted(operation.summary)},
    tag: ${quoted(operation.tag)},
    kind: ${quoted(operation.kind)},
  },`,
  )
  .join("\n");

const source = `// AUTO-GENERATED by scripts/generate-code.ts. Do not edit.
import * as Operations from "../services/affinity.ts";

export const operationRegistry = {
${entries}
} as const;

export type OperationName = keyof typeof operationRegistry;
export type OperationKind = (typeof operationRegistry)[OperationName]["kind"];
`;

await Bun.write(`${import.meta.dir}/../src/code/registry.ts`, source);
